import sqlite3

print('^'*80)
print("\n")
print("# Copyright 2019 Yoana Stankova")
print('\n')
print("\n")
print ('-'*80)
print('Craiglockhart Mental Hospital'.title())
print("\n")
print ('^'*80)
print ("Welcome to Craiglockhart Mental Hospital.") 
print ('\n')
print ("If you would like to find records of doctors, type in 'doctors', for patients - 'patients'.")
print ("All of our staff and patients are assigned unique ids. If you want to conduct a search by id, type 'patient/doctor-id'.")
print("If you are stuck at some point, just type in 'guide'.")
print('\n')

while True:
    anw = input("Enter query:")
    print('\n')
    if anw == "instructions":
        print ("If you would like to find records of doctors, type in 'doctors, for patients - 'patients'.")
        print ("All of our staff and patients are assigned unique ids. If you want to conduct a search by id, type 'patient/doctor-id'. If you want to search by first/last name, age, diagnosis, military status, social status, or occupation, make sure to type in the key word, putting a hyphen in two word phrases, e.g.'first-name'.") 
    elif anw == "patients":
        print("id: 1")
        print("First Name: John") 
        print("Last Name: Layard")
        print("Age: 26")
        print("Diagnosis: none")
        print("Military Status: none")
        print("Social Status: none")
        print("Occupation: none")
        print("\n")
        print("id: 2")
        print("First Name: Siegfried") 
        print("Last Name: Sassoon")
        print("Age: 31")
        print("Diagnosis: shell-shocked")
        print("Military Status: officer")
        print("Social Status: upper-class aristocrat")
        print("Occupation: war poet")
        print("\n")
        print("id: 3")
        print("First Name: David") 
        print("Last Name: Burns")
        print("Age: 22")
        print("Diagnosis: cannot eat without throwing up")
        print("Military Status: officer")
        print("Social Status: none")
        print("Occupation: none")
        print("\n")
        print("id: 4")
        print("First Name: Billy") 
        print("Last Name: Prior")
        print("Age: 23")
        print("Diagnosis: mutism, asthma")
        print("Military Status: officer")
        print("Social Status: working class")
        print("Occupation: none")
        print("\n")
        print("id: 5")
        print("First Name: none") 
        print("Last Name: Anderson")
        print("Age: 30")
        print("Diagnosis: unable to tolerate the sight of blood")
        print("Military Status: surgeon")
        print("Social Status: none")
        print("Occupation: none")
        print("\n")
        print("id: 6")
        print("First Name: none") 
        print("Last Name: Willard")
        print("Age: 25")
        print("Diagnosis: hypochindriasis")
        print("Military Status: none")
        print("Social Status: none")
        print("Occupation: none")
        print("\n")
    elif anw == "doctors":
        print("id: 1")
        print("age: old")
        print("occupation: psychiatrist")
        print("\n")
        print("id: 2")
        print("age: old")
        print("occupation: psychiatrist (has war neurosis)")
        print("\n")
    elif anw.lower() == "john" or anw.lower() == "layard" or anw.lower() == "patient-1":
        print("id: 1")
        print("First Name: John") 
        print("Last Name: Layard")
        print("Age: 26")
        print("Diagnosis: none")
        print("Military Status: none")
        print("Social Status: none")
        print("Occupation: none")
        print("\n")
    elif anw.lower() == "siegfried" or anw.lower() == "sassoon" or anw.lower() == "patient-2":
        print("id: 2")
        print("First Name: Siegfried") 
        print("Last Name: Sassoon")
        print("Age: 31")
        print("Diagnosis: shell-shocked")
        print("Military Status: officer")
        print("Social Status: upper-class aristocrat")
        print("Occupation: war poet")
        print("\n")
    elif anw.lower() == "david" or anw.lower() == "burns" or anw.lower() == "patient-3":
        print("id: 3")
        print("First Name: David") 
        print("Last Name: Burns")
        print("Age: 22")
        print("Diagnosis: cannot eat without throwing up")
        print("Military Status: officer")
        print("Social Status: none")
        print("Occupation: none")
        print("\n")
    elif anw.lower() == "billy" or anw.lower() == "prior" or anw.lower() == "patient-4":
        print("id: 4")
        print("First Name: Billy") 
        print("Last Name: Prior")
        print("Age: 23")
        print("Diagnosis: mutism, asthma")
        print("Military Status: officer")
        print("Social Status: working class")
        print("Occupation: none")
        print("\n")
    elif anw.lower() == "anderson" or anw.lower() == "patient-5":
        print("id: 5")
        print("First Name: none") 
        print("Last Name: Anderson")
        print("Age: 30")
        print("Diagnosis: unable to tolerate the sight of blood")
        print("Military Status: surgeon")
        print("Social Status: none")
        print("Occupation: none")
        print("\n")
    elif anw.lower() == "willard" or anw.lower() == "patient-6":
        print("id: 6")
        print("First Name: none") 
        print("Last Name: Willard")
        print("Age: 25")
        print("Diagnosis: hypochindriasis")
        print("Military Status: none")
        print("Social Status: none")
        print("Occupation: none")
        print("\n")
    elif anw.lower() == "bryce" or anw.lower() == "doctor-1":
        print("id: 1")
        print("age: old")
        print("occupation: psychiatrist")
        print("\n")
    elif anw.lower() == "rivers" or anw.lower() == "doctor-2":
        print("id: 2")
        print("age: old")
        print("occupation: psychiatrist (has war neurosis)")
        print("\n")
    elif anw.lower() == "guide":
        print ("If you would like to find records of doctors, type in 'doctors', for patients - 'patients'.")
        print ("All of our staff and patients are assigned unique ids. If you want to conduct a search by id, type 'patient/doctor-id'.")
    else:
        print ("Invalid input. Try again...")
        print ('\n')
        
